### ISSUE TITLE
CouldNotSendNotification thrown when empty array is returned

### ISSUE THREAD

**Issue by gboor** [enniel/laravel-fcm-notification-channel#6]
I have various notifications that get sent to users via a number of channels depending on how they registered. It can be APN, FCM or email. Not all notifications will be sent via all channels and when no FCM user can be found, routeNotificationForFCM returns an empty array.

The APN and Email channels handle this fine; if there are no recipients (empty array), the notification is not sent via these channels.

This FCM library, however, throws an exception when that occurs, while it is a perfectly viable flow.

For comparison, here is the APN channel source;

```
        $tokens = (array) $notifiable->routeNotificationFor('apn');
        if (! $tokens) {
            return;
        }

        $message = $notification->toApn($notifiable);
        if (! $message) {
            return;
        }

... [actual sending] ...
```

vs the FCM source

```
        $message = $notification->toFCM($notifiable);
        if ($message->recipientNotGiven()) {
            if (! $to = $notifiable->routeNotificationFor('FCM')) {
                throw CouldNotSendNotification::missingRecipient();
            }
            $message->to($to);
        }
... [actual sending] ...
```

Could this please be resolved to behave like the other notification channels out there?

**Comment by enniel** [comment]
@gboor Fixed in 0.1.0. The exception will not be thrown to an empty array.
